# Generated by Django 4.0.3 on 2022-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youcookuserprofile',
            old_name='profile_destcription',
            new_name='profile_description',
        ),
        migrations.AlterField(
            model_name='youcookuserprofile',
            name='first_name',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='youcookuserprofile',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
    ]
