# Generated by Django 4.0.3 on 2022-04-15 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_destcription_youcookuserprofile_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youcookuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
